[workspace]
publish = false
git_only = true
semver_check = false
git_release_enable = true
git_tag_enable = true
changelog_update = true
changelog_path = "./CHANGELOG.md"
changelog_config = "./cliff.toml"
release_always = false
release_commits = "^(feat|fix|perf|refactor)[:(]"
